name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with: {python-version: '3.10'}
      - run: pip install -r requirements.txt
      - run: pytest -q
      - name: Smoke test simulation
        run: |
          timeout 30s python main.py --simulate || true
          echo "Smoke simulation test completed"